Apply xcookie template

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -6,7 +6,17 @@
         This file should need minimal modification.
 
         Template for this files is from
-        ~/misc/templates/PYPKG/.gitlab-ci.yml
+        ~/misc/templates/kwplot/.gitlab-ci.yml
+
+        Templates used in:
+
+        ~/code/kwplot/.gitlab-ci.yml
+        ~/code/kwimage/.gitlab-ci.yml
+        ~/code/kwarray/.gitlab-ci.yml
+        ~/code/kwcoco/.gitlab-ci.yml
+
+        ~/code/ndsampler/.gitlab-ci.yml
+
 
         Enable the opencv-hack if needed, and turn on/off the desired versions
         of Python.
@@ -55,7 +65,8 @@ stages:
         - python -V  # Print out python version for debugging
 
     script: 
-        - python setup.py bdist_wheel --universal
+        #- python setup.py bdist_wheel --universal
+        - python setup.py bdist_wheel 
 
     artifacts:
         paths:
@@ -81,10 +92,10 @@ stages:
     # Coverage is a regex that will parse the coverage from the test stdout
     coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
 
-    except:
-        refs:
-          - release 
-          - tags
+    #except:
+    #    refs:
+    #      - release 
+    #      - tags
     #    changes:
     #        - README.rst
     #        - CHANGELOG.md
@@ -101,15 +112,6 @@ stages:
     pip install pip setuptools -U
     python -V  # Print out python version for debugging
 
-._install_strict_minimal_requirements: &_install_strict_minimal_requirements |-
-    ./dev/make_strict_req.sh
-    pip install -r requirements-strict/runtime.txt -r requirements-strict/tests.txt -r requirements-strict/headless.txt
-
-
-._install_strict_full_requirements: &_install_strict_full_requirements |-
-    ./dev/make_strict_req.sh
-    pip install -r requirements-strict/optional.txt -r requirements-strict/runtime.txt -r requirements-strict/tests.txt -r requirements-strict/headless.txt
-
 
 .test_minimal_strict_template: &test_minimal_strict_template
     # Tags define which runners will accept which jobs
@@ -118,8 +120,8 @@ stages:
 
     before_script:
         - *_setup_virtualenv_template
-        - *_install_strict_minimal_requirements
-        - pip install .[tests,headless]  
+        - pip install .[tests-strict]                   # kwplot +COMMENT_IF(cv2)
+        #- pip install .[tests-strict,headless-strict]  # kwplot +UNCOMMENT_IF(cv2)
 
 
 .test_full_strict_template: &test_full_strict_template
@@ -129,8 +131,8 @@ stages:
 
     before_script:
         - *_setup_virtualenv_template
-        - *_install_strict_full_requirements
-        - pip install .[all,headless]
+        - pip install .[all-strict]                   # kwplot +COMMENT_IF(cv2)
+        #- pip install .[all-strict,headless-strict]  # kwplot +UNCOMMENT_IF(cv2)
 
 .test_minimal_loose_template: &test_minimal_loose_template
     # Tags define which runners will accept which jobs
@@ -139,7 +141,8 @@ stages:
 
     before_script:
         - *_setup_virtualenv_template
-        - pip install .[tests,headless]  
+        - pip install .[tests]            # kwplot +COMMENT_IF(cv2)
+        #- pip install .[tests,headless]  # kwplot +UNCOMMENT_IF(cv2)
 
 
 .test_full_loose_template: &test_full_loose_template
@@ -149,7 +152,8 @@ stages:
 
     before_script:
         - *_setup_virtualenv_template
-        - pip install .[all,headless]
+        - pip install .[all]            # kwplot +COMMENT_IF(cv2)
+        #- pip install .[all,headless]  # kwplot +UNCOMMENT_IF(cv2)
 
 
 
@@ -161,26 +165,27 @@ stages:
         gpgsign
 
     script: 
-        - export GPG_EXECUTABLE=gpg
-        - export GPG_KEYID=$(cat dev/public_gpg_key)
-        - echo "GPG_KEYID = $GPG_KEYID"
-        # source repo-specific secrets
-        # VARNAME_CI_SECRET points to a protected variable only available on main and release branch
-        - source dev/secrets_configuration.sh
-        - CI_SECRET=${!VARNAME_CI_SECRET}
-        - $GPG_EXECUTABLE --version
-        - openssl version
-        - $GPG_EXECUTABLE --list-keys
-        - $GPG_EXECUTABLE --list-keys
-        # Decrypt and import GPG Keys / trust
-        - GLKWS=$CI_SECRET openssl enc -aes-256-cbc -pbkdf2 -md SHA512 -pass env:GLKWS -d -a -in dev/ci_public_gpg_key.pgp.enc | $GPG_EXECUTABLE --import 
-        - GLKWS=$CI_SECRET openssl enc -aes-256-cbc -pbkdf2 -md SHA512 -pass env:GLKWS -d -a -in dev/gpg_owner_trust.enc | $GPG_EXECUTABLE --import-ownertrust
-        - GLKWS=$CI_SECRET openssl enc -aes-256-cbc -pbkdf2 -md SHA512 -pass env:GLKWS -d -a -in dev/ci_secret_gpg_subkeys.pgp.enc | $GPG_EXECUTABLE --import 
-        - $GPG_EXECUTABLE --list-keys  || echo "first one fails for some reason"
-        - $GPG_EXECUTABLE --list-keys  
-        # The publish script only builds wheels and does gpg signing if DO_UPLOAD is no
-        - pip install requests[security] twine 
-        - MB_PYTHON_TAG=$MB_PYTHON_TAG DO_GPG=True GPG_KEYID=$GPG_KEYID TWINE_PASSWORD=$TWINE_PASSWORD TWINE_USERNAME=$TWINE_USERNAME GPG_EXECUTABLE=$GPG_EXECUTABLE DEPLOY_BRANCH=release DO_TAG=False DO_UPLOAD=False ./publish.sh 
+        - |
+          export GNUPGHOME=$(mktemp -d)
+          export GPG_EXECUTABLE=gpg
+          export GPG_KEYID=$(cat dev/public_gpg_key)
+          echo "GPG_KEYID = $GPG_KEYID"
+          source dev/secrets_configuration.sh
+          # note the variable pointed to by VARNAME_CI_SECRET is a protected variables only available on main and release branch
+          CI_SECRET=${!VARNAME_CI_SECRET}
+          $GPG_EXECUTABLE --version
+          openssl version
+          $GPG_EXECUTABLE --list-keys
+          $GPG_EXECUTABLE --list-keys
+          # Decrypt and import GPG Keys / trust
+          GLKWS=$CI_SECRET openssl enc -aes-256-cbc -pbkdf2 -md SHA512 -pass env:GLKWS -d -a -in dev/ci_public_gpg_key.pgp.enc | $GPG_EXECUTABLE --import 
+          GLKWS=$CI_SECRET openssl enc -aes-256-cbc -pbkdf2 -md SHA512 -pass env:GLKWS -d -a -in dev/gpg_owner_trust.enc | $GPG_EXECUTABLE --import-ownertrust
+          GLKWS=$CI_SECRET openssl enc -aes-256-cbc -pbkdf2 -md SHA512 -pass env:GLKWS -d -a -in dev/ci_secret_gpg_subkeys.pgp.enc | $GPG_EXECUTABLE --import 
+          $GPG_EXECUTABLE --list-keys  || echo "first one fails for some reason"
+          $GPG_EXECUTABLE --list-keys  
+          # The publish script only builds wheels and does gpg signing if DO_UPLOAD is no
+          pip install requests[security] twine 
+          DO_GPG=True GPG_KEYID=$GPG_KEYID TWINE_PASSWORD=$TWINE_PASSWORD TWINE_USERNAME=$TWINE_USERNAME GPG_EXECUTABLE=$GPG_EXECUTABLE DEPLOY_BRANCH=release DO_TAG=False DO_UPLOAD=False ./publish.sh
 
     artifacts:
         paths:
@@ -206,36 +211,37 @@ stages:
         deploy
 
     script: 
-        - export GPG_EXECUTABLE=gpg
-        - export GPG_KEYID=$(cat dev/public_gpg_key)
-        - echo "GPG_KEYID = $GPG_KEYID"
-        - source dev/secrets_configuration.sh
-        # source repo-specific secrets
-        # VARNAME_CI_SECRET points to a protected variable only available on main and release branch
-        - source dev/secrets_configuration.sh
-        - CI_SECRET=${!VARNAME_CI_SECRET}
-        - PUSH_TOKEN=${!VARNAME_PUSH_TOKEN}
-        - $GPG_EXECUTABLE --version
-        - openssl version
-        - $GPG_EXECUTABLE --list-keys
-        - $GPG_EXECUTABLE --list-keys
-        # Decrypt and import GPG Keys / trust
-        - GLKWS=$CI_SECRET openssl enc -aes-256-cbc -pbkdf2 -md SHA512 -pass env:GLKWS -d -a -in dev/ci_public_gpg_key.pgp.enc | $GPG_EXECUTABLE --import 
-        - GLKWS=$CI_SECRET openssl enc -aes-256-cbc -pbkdf2 -md SHA512 -pass env:GLKWS -d -a -in dev/gpg_owner_trust.enc | $GPG_EXECUTABLE --import-ownertrust
-        - GLKWS=$CI_SECRET openssl enc -aes-256-cbc -pbkdf2 -md SHA512 -pass env:GLKWS -d -a -in dev/ci_secret_gpg_subkeys.pgp.enc | $GPG_EXECUTABLE --import 
-        - $GPG_EXECUTABLE --list-keys  || echo "first one fails for some reason"
-        - $GPG_EXECUTABLE --list-keys  
-        # Install twine
-        - pip install six pyopenssl ndg-httpsclient pyasn1 -U 
-        - pip install requests[security] twine 
-        # Execute the publish script for real this time
-        - MB_PYTHON_TAG=$MB_PYTHON_TAG DO_GPG=True GPG_KEYID=$GPG_KEYID TWINE_PASSWORD=$TWINE_PASSWORD TWINE_USERNAME=$TWINE_USERNAME GPG_EXECUTABLE=$GPG_EXECUTABLE CURRENT_BRANCH=release DEPLOY_BRANCH=release DO_TAG=True DO_UPLOAD=True ./publish.sh || echo "upload already exists"
-        - | 
+        - |
+            export GNUPGHOME=$(mktemp -d)
+            export GPG_EXECUTABLE=gpg
+            export GPG_KEYID=$(cat dev/public_gpg_key)
+            echo "GPG_KEYID = $GPG_KEYID"
+            # VARNAME_CI_SECRET points to a protected variable only available on main and release branch
+            source dev/secrets_configuration.sh
+            CI_SECRET=${!VARNAME_CI_SECRET}
+            PUSH_TOKEN=${!VARNAME_PUSH_TOKEN}
+            TWINE_PASSWORD=${!VARNAME_TWINE_PASSWORD}
+            TWINE_USERNAME=${!VARNAME_TWINE_USERNAME}
+            $GPG_EXECUTABLE --version
+            openssl version
+            $GPG_EXECUTABLE --list-keys
+            $GPG_EXECUTABLE --list-keys
+            # Decrypt and import GPG Keys / trust
+            GLKWS=$CI_SECRET openssl enc -aes-256-cbc -pbkdf2 -md SHA512 -pass env:GLKWS -d -a -in dev/ci_public_gpg_key.pgp.enc | $GPG_EXECUTABLE --import 
+            GLKWS=$CI_SECRET openssl enc -aes-256-cbc -pbkdf2 -md SHA512 -pass env:GLKWS -d -a -in dev/gpg_owner_trust.enc | $GPG_EXECUTABLE --import-ownertrust
+            GLKWS=$CI_SECRET openssl enc -aes-256-cbc -pbkdf2 -md SHA512 -pass env:GLKWS -d -a -in dev/ci_secret_gpg_subkeys.pgp.enc | $GPG_EXECUTABLE --import 
+            $GPG_EXECUTABLE --list-keys  || echo "first one fails for some reason"
+            $GPG_EXECUTABLE --list-keys  
+            # Install twine
+            pip install six pyopenssl ndg-httpsclient pyasn1 -U 
+            pip install requests[security] twine 
+            # Execute the publish script for real this time
+            TWINE_REPOSITORY_URL=https://upload.pypi.org/legacy/ DO_GPG=True GPG_KEYID=$GPG_KEYID TWINE_PASSWORD=$TWINE_PASSWORD TWINE_USERNAME=$TWINE_USERNAME GPG_EXECUTABLE=$GPG_EXECUTABLE CURRENT_BRANCH=release DEPLOY_BRANCH=release DO_TAG=True DO_UPLOAD=True ./publish.sh || echo "upload already exists"
             # Have the server git-tag the release and push the tags
-            export VERSION=$(python -c "import setup; print(setup.VERSION)")
-            # do sed twice to handle the case of https clone with and without a read token
+            VERSION=$(python -c "import setup; print(setup.VERSION)")
+        # do sed twice to handle the case of https clone with and without a read token
+        - | 
             URL_HOST=$(git remote get-url origin | sed -e 's|https\?://.*@||g' | sed -e 's|https\?://||g' | sed -e 's|git@||g' | sed -e 's|:|/|g')
-            git push --tags $DEPLOY_REMOTE
             echo "URL_HOST = $URL_HOST"
             # A git config user name and email is required. Set if needed.
             if [[ "$(git config user.email)" == "" ]]; then
@@ -253,16 +259,16 @@ stages:
                 git tag $TAG_NAME -m "tarball tag $VERSION"
                 git push --tags "https://git-push-token:${PUSH_TOKEN}@${URL_HOST}"
             fi
-            
+
     only:
         refs:
             - release
 
 
-## Aliases for the images that run the tests
-#.image_python3_10: &image_python3_10
-#    #gitlab.kitware.com:4567/computer-vision/ci-docker/gl-python:3.10
-#    python:3.10
+# Aliases for the images that run the tests
+.image_python3_10: &image_python3_10
+    #gitlab.kitware.com:4567/computer-vision/ci-docker/gl-python:3.10
+    python:3.10
 .image_python39: &image_python39
     #gitlab.kitware.com:4567/computer-vision/ci-docker/gl-python:3.9
     python:3.9
@@ -278,9 +284,9 @@ stages:
 .image_python35: &image_python35
     #gitlab.kitware.com:4567/computer-vision/ci-docker/gl-python:3.5
     python:3.5
-#.image_python27: &image_python27
-#    #gitlab.kitware.com:4567/computer-vision/ci-docker/gl-python:2.7
-#    python:2.7
+.image_python27: &image_python27
+    #gitlab.kitware.com:4567/computer-vision/ci-docker/gl-python:2.7
+    python:2.7
     
 
 
@@ -288,47 +294,47 @@ stages:
 # Define the actual jobs
 
 
-## ---------------
-## Python 3.10 Jobs
+# ---------------
+# Python 3.10 Jobs
 
 
-#build/cp3_10-cp3_10-linux:
-#    <<: 
-#        - *build_template
-#    image:
-#        *image_python3_10
+build/cp3_10-cp3_10-linux:
+    <<: 
+        - *build_template
+    image:
+        *image_python3_10
 
-#test_full_loose/cp3_10-cp3_10-linux:
-#    <<: 
-#        - *test_full_loose_template
-#    image:
-#        *image_python3_10
-#    needs: 
-#        -  build/cp3_10-cp3_10-linux
+test_full_loose/cp3_10-cp3_10-linux:
+    <<: 
+        - *test_full_loose_template
+    image:
+        *image_python3_10
+    needs: 
+        -  build/cp3_10-cp3_10-linux
 
-#test_minimal_loose/cp3_10-cp3_10-linux:
-#    <<: 
-#        - *test_minimal_loose_template
-#    image:
-#        *image_python3_10
-#    needs: 
-#        -  build/cp3_10-cp3_10-linux
+test_minimal_loose/cp3_10-cp3_10-linux:
+    <<: 
+        - *test_minimal_loose_template
+    image:
+        *image_python3_10
+    needs: 
+        -  build/cp3_10-cp3_10-linux
 
-#test_full_strict/cp3_10-cp3_10-linux:
-#    <<: 
-#        - *test_full_strict_template
-#    image:
-#        *image_python3_10
-#    needs: 
-#        -  build/cp3_10-cp3_10-linux
+test_full_strict/cp3_10-cp3_10-linux:
+    <<: 
+        - *test_full_strict_template
+    image:
+        *image_python3_10
+    needs: 
+        -  build/cp3_10-cp3_10-linux
 
-#test_minimal_strict/cp3_10-cp3_10-linux:
-#    <<: 
-#        - *test_minimal_strict_template
-#    image:
-#        *image_python3_10
-#    needs: 
-#        -  build/cp3_10-cp3_10-linux
+test_minimal_strict/cp3_10-cp3_10-linux:
+    <<: 
+        - *test_minimal_strict_template
+    image:
+        *image_python3_10
+    needs: 
+        -  build/cp3_10-cp3_10-linux
 
 # ---------------
 # Python 3.9 Jobs
@@ -518,48 +524,48 @@ test_minimal_strict/cp36-cp36m-linux:
 # Python 3.5 Jobs
 
 
-build/cp35-cp35m-linux:
-    <<: 
-        - *build_template
-    image:
-        *image_python35
+#build/cp35-cp35m-linux:
+#    <<: 
+#        - *build_template
+#    image:
+#        *image_python35
 
-test_full_loose/cp35-cp35m-linux:
-    <<: 
-        - *test_full_loose_template
-    image:
-        *image_python35
-    needs: 
-        -  build/cp35-cp35m-linux
+#test_full_loose/cp35-cp35m-linux:
+#    <<: 
+#        - *test_full_loose_template
+#    image:
+#        *image_python35
+#    needs: 
+#        -  build/cp35-cp35m-linux
 
-test_minimal_loose/cp35-cp35m-linux:
-    <<: 
-        - *test_minimal_loose_template
-    image:
-        *image_python35
-    needs: 
-        -  build/cp35-cp35m-linux
+#test_minimal_loose/cp35-cp35m-linux:
+#    <<: 
+#        - *test_minimal_loose_template
+#    image:
+#        *image_python35
+#    needs: 
+#        -  build/cp35-cp35m-linux
 
-test_full_strict/cp35-cp35m-linux:
-    <<: 
-        - *test_full_strict_template
-    image:
-        *image_python35
-    needs: 
-        -  build/cp35-cp35m-linux
+#test_full_strict/cp35-cp35m-linux:
+#    <<: 
+#        - *test_full_strict_template
+#    image:
+#        *image_python35
+#    needs: 
+#        -  build/cp35-cp35m-linux
 
-test_minimal_strict/cp35-cp35m-linux:
-    <<: 
-        - *test_minimal_strict_template
-    image:
-        *image_python35
-    needs: 
-        -  build/cp35-cp35m-linux
+#test_minimal_strict/cp35-cp35m-linux:
+#    <<: 
+#        - *test_minimal_strict_template
+#    image:
+#        *image_python35
+#    needs: 
+#        -  build/cp35-cp35m-linux
 
 
 
-## ---------------
-## Python 2.7 Jobs
+# ---------------
+# Python 2.7 Jobs
 
 
 #build/cp27-cp27m-linux:
@@ -608,9 +614,9 @@ test_minimal_strict/cp35-cp35m-linux:
             # Commands to help developers debug pipelines on their local machine
             # Grab the base docker image, (forwarding your ssh credentials), clone
             # the watch repo, create the environment, and run the tests. 
-            docker login gitlab.kitware.com:4567
+            #docker login gitlab.kitware.com:4567
 
-            IMAGE_NAME=gitlab.kitware.com:4567/computer-vision/ci-docker/gl-python:3.7
+            IMAGE_NAME=gitlab.kitware.com:4567/computer-vision/ci-docker/gl-python:3.8
             docker run -v $PWD:/io:ro -v $HOME/.cache/pip:/pip_cache -it $IMAGE_NAME bash
             # Will need to chmod things afterwords
             export PIP_CACHE_DIR=/pip_cache
@@ -634,12 +640,10 @@ test_minimal_strict/cp35-cp35m-linux:
             #pip install pip setuptools -U
 
             # STRICT VARIANT
-            ./dev/make_strict_req.sh
-            pip install -r requirements-strict.txt -r requirements-strict/headless.txt
-            pip install -e .
+            pip install -e .[runtime-strict,headless-strict]
             ./run_tests.py
 
             # LOOSE VARIANT
             pip install -r requirements.txt
-            pip install -e .[tests,headless]
+            pip install -e .
             ./run_tests.py
